//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XenAdmin {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InvisibleMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvisibleMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XenAdmin.InvisibleMessages", typeof(InvisibleMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 https://{0}/index.html?transactionID={1} 的本地化字符串。
        /// </summary>
        public static string ACTIVATION_FORM_URL {
            get {
                return ResourceManager.GetString("ACTIVATION_FORM_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 activate.vmd.citrix.com 的本地化字符串。
        /// </summary>
        public static string ACTIVATION_SERVER {
            get {
                return ResourceManager.GetString("ACTIVATION_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://{0}/reactivation_server.php 的本地化字符串。
        /// </summary>
        public static string ACTIVATION_URL {
            get {
                return ResourceManager.GetString("ACTIVATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://updates.xensource.com/[vGate]/{0}/XenCenter 的本地化字符串。
        /// </summary>
        public static string CHECK_FOR_UPDATES_URL {
            get {
                return ResourceManager.GetString("CHECK_FOR_UPDATES_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://xenserver.org/ 的本地化字符串。
        /// </summary>
        public static string COMMUNITY_URL {
            get {
                return ResourceManager.GetString("COMMUNITY_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://cis.citrix.com/legal/ 的本地化字符串。
        /// </summary>
        public static string HEALTH_CHECK_PRIVACY_STATEMENT_URL {
            get {
                return ResourceManager.GetString("HEALTH_CHECK_PRIVACY_STATEMENT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver 的本地化字符串。
        /// </summary>
        public static string HOMEPAGE {
            get {
                return ResourceManager.GetString("HOMEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HomePage.mht 的本地化字符串。
        /// </summary>
        public static string HOMEPAGE_FILENAME {
            get {
                return ResourceManager.GetString("HOMEPAGE_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 www.citrix.com/xenserverenterprise 的本地化字符串。
        /// </summary>
        public static string HTTP_LICENSES {
            get {
                return ResourceManager.GetString("HTTP_LICENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://support.citrix.com/article/CTX141433 的本地化字符串。
        /// </summary>
        public static string ISL_DEPRECATION_URL {
            get {
                return ResourceManager.GetString("ISL_DEPRECATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iso 的本地化字符串。
        /// </summary>
        public static string ISO_UPDATE {
            get {
                return ResourceManager.GetString("ISO_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserverenterprise 的本地化字符串。
        /// </summary>
        public static string LICENSE_EXPIRY_WEBPAGE {
            get {
                return ResourceManager.GetString("LICENSE_EXPIRY_WEBPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/downloads/licensing/license-server 的本地化字符串。
        /// </summary>
        public static string LICENSE_SERVER_DOWNLOAD_LINK {
            get {
                return ResourceManager.GetString("LICENSE_SERVER_DOWNLOAD_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 en-US 的本地化字符串。
        /// </summary>
        public static string LOCALE {
            get {
                return ResourceManager.GetString("LOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [vGate Console].log 的本地化字符串。
        /// </summary>
        public static string LOG_FILENAME {
            get {
                return ResourceManager.GetString("LOG_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -mapid {0} {1} 的本地化字符串。
        /// </summary>
        public static string MAINWINDOW_HELP_PARAMS {
            get {
                return ResourceManager.GetString("MAINWINDOW_HELP_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help\XenCenter.chm 的本地化字符串。
        /// </summary>
        public static string MAINWINDOW_HELP_PATH {
            get {
                return ResourceManager.GetString("MAINWINDOW_HELP_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home.htm 的本地化字符串。
        /// </summary>
        public static string MAINWINDOW_HOME_PATH {
            get {
                return ResourceManager.GetString("MAINWINDOW_HOME_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserverenterprise 的本地化字符串。
        /// </summary>
        public static string OUT_OF_DATE_WEBSITE {
            get {
                return ResourceManager.GetString("OUT_OF_DATE_WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/buy/partnerlocator.html 的本地化字符串。
        /// </summary>
        public static string PARTNEROFFERS_URL {
            get {
                return ResourceManager.GetString("PARTNEROFFERS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://wiki.xenserver.org/XenCenter_Plugins 的本地化字符串。
        /// </summary>
        public static string PLUGINS_URL {
            get {
                return ResourceManager.GetString("PLUGINS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://citrix.com/English/aboutCitrix/legal/privacyStatement.asp?ntref=hp_nav_US 的本地化字符串。
        /// </summary>
        public static string PRIVACY {
            get {
                return ResourceManager.GetString("PRIVACY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://support.citrix.com/ 的本地化字符串。
        /// </summary>
        public static string SUPPORT_URL {
            get {
                return ResourceManager.GetString("SUPPORT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver/le/features/ad 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_AD {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver/le/features/alerts 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_ALERTS {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_ALERTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver/le/features/storagemigration 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_CPM {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_CPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver/le/features/cpus 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_CPUMASKING {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_CPUMASKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver/le/features/dmc 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_DMC {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_DMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver/le/features/dr 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_DR {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver/le/features/storage 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_ENHANCEDSR {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_ENHANCEDSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver/le/features 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_GENERAL {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver/le/features/gpu 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_GPU {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver/le/features/ha 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_HA {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_HA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver/le/features/performance 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_PERFORMANCE {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_PERFORMANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver/le/features/rbac 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_RBAC {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_RBAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver/le/features/vapps 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_VM_APPLIANCES {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_VM_APPLIANCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/xenserver/le/features/vmpr 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_VM_PROTECTION {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_VM_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_VMSS {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_VMSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.halsign.com/ 的本地化字符串。
        /// </summary>
        public static string UPSELL_LEARNMOREURL_WLB {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_WLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://store.citrix.com/XSInProduct 的本地化字符串。
        /// </summary>
        public static string UPSELL_SA {
            get {
                return ResourceManager.GetString("UPSELL_SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://support.citrix.com/article/CTX137335 的本地化字符串。
        /// </summary>
        public static string VMPR_DEPRECATION_URL {
            get {
                return ResourceManager.GetString("VMPR_DEPRECATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://support.citrix.com/article/CTX137334 的本地化字符串。
        /// </summary>
        public static string WSS_DEPRECATION_URL {
            get {
                return ResourceManager.GetString("WSS_DEPRECATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 xensearch 的本地化字符串。
        /// </summary>
        public static string XEN_SEARCH {
            get {
                return ResourceManager.GetString("XEN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 xsupdate 的本地化字符串。
        /// </summary>
        public static string XEN_UPDATE {
            get {
                return ResourceManager.GetString("XEN_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.citrix.com/TryXenDesktop 的本地化字符串。
        /// </summary>
        public static string XENDESKTOP_URL {
            get {
                return ResourceManager.GetString("XENDESKTOP_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://updates.xensource.com/XenServer/updates.xml 的本地化字符串。
        /// </summary>
        public static string XENSERVER_UPDATE_URL {
            get {
                return ResourceManager.GetString("XENSERVER_UPDATE_URL", resourceCulture);
            }
        }
    }
}
